### ISSUE TITLE
Score audio file

### ISSUE THREAD

**Issue by canhbd** [doheejin/HiPAMA#1]
Hello, thank for your sharing this repo

How can I pass an audio file. The output is the score of the audio file: **accuracy**, **completeness**, **fluency**, **prosodic** and **total**

Thank you!

**Comment by DreamSoul1** [comment]
II have the same issue. Have you resolved it?

**Comment by doheejin** [comment]
Thank you for the question!

We used the same dataset as the baseline model, GOPT. Please download and configure the data in the same way as this repository: https://github.com/YuanGongND/gopt/tree/master/data. 

To use your audio dataset other than the speechocean762, generate the Godness of Pronunciation (GOP) features first and then convert the features to sequences for model input, as described in the aforementioned repository.

**Comment by canhbd** [comment]
Thank you!
